name: Create Release

on:
  push:
   branches:
     - master
   tags:
     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        generate_release_notes: true
    - name: Get Release
      id: get-release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Send Slack Message
      id: send-slack-message
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        payload: |
          {
            "release_name": "${{ steps.get-release.outputs.name }}",
            "release_notes": "${{ steps.get-release.outputs.body }}"
          }
